language: csharp
solution: Monkeyspeak.sln
sudo: true
bundler_args: "--retry 5"

matrix:
    include:
        - dotnet: 1.1.5
          mono: none
          env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
        - mono: latest
#branches:
#  except:
#    - /^*-v[0-9]/

notifications:
    email:
        recipients:
            - $EMAIL
        on_success: never
        on_failure: always

before_install:
- sudo apt-get install rar

install:
- nuget install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
- nuget restore Monkeyspeak.sln

script:
- xbuild /p:Configuration=Release Monkeyspeak.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./Monkeyspeak.Tests/bin/Release/Monkeyspeak.Tests.dll


before_deploy:
    - export GIT_TAG="$TRAVIS_BRANCH-Build-$TRAVIS_BUILD_ID"
    - git tag $GIT_TAG -m "Generated tag from TravisCI for build $TRAVIS_BUILD_ID"
  
deploy:
  provider: releases
  api_key:
    secure: SBhVhOQHU6Q6EQG07td5VLX6Re0hb8iZsyRl/8JU6f/ih+CSsiEMFdSgwwjuIRGZznrvtLQS9Uk4x43p3xkTl/pWiYxNRA2+Nj6oEL8rITCmlHK1T/YcaksP9E4pDBEJaZBQ7W7hpMCK8WvZY8bOO0g6ktsPGzInjeYY/kxWGI7pnM+iZFG8vK+AYnGYxbPPg4iH8ogiwymj657bOSzKltY3jV+SBSI8WylIjyetUDYy5OF4azI7q9w6wvrGBGEkteVcKWgGJozwjz0fKRVUsWZZFs2y51PrJ/j3zPW+lbD8l05Ih7ElS5Uclpuo/JYPGJHBVxclC6UfgsDwcrGh6PTSzdv49TMwqnfBxzKS1hmj5fsR9L7Qix7YnznUBpQ0VazZl9WoBIs9OAHkYJKpn0w0Kp/0Mi9BiKsnNpNhC/fl9C8ZRooyLpiQrnij9I0e3YNQ7WAXx8QuJbm3zjXrmAfmWDt+MFmlvrvhf4PFMhFdp6Oh5az+EhiTCJyfrNpmYAbakM8NJAWNkrJwLMwkQ3ZeWgfO88O7orVLOgOJ8kwBxNov9o2J6Ba8wxQ3fZhxlFncJEWJcMN/TMkEVkLMow83XXlsuX/EBPOaj9Q9sMslD38kMrQWy5edFySXv8UbfhCeomx2Pl7d8zqfVGtrLRKfTPJCTP2366uuRKIfdhA=
  file_glob: true
  file: 
    - $TRAVIS_BUILD_DIR/Monkeyspeak/bin/Release/*.rar
    - $TRAVIS_BUILD_DIR/msxc/bin/Release/*.rar
  skip_cleanup: true
  on:
    repo: captkirk88/monkeyspeak
