language: csharp
solution: Monkeyspeak.sln
mono: latest
branches:
  only:
  - master
  - stable
install:
  - nuget restore Monkeyspeak.sln
script:
# clear pre and post build rar commands due to them being batch and incompatible with linux
  - xbuild /p:Configuration=Release Monkeyspeak.sln