language: csharp
solution: Monkeyspeak.sln
mono: latest
branches:
  only:
  - master
  - stable
install:
  - nuget restore Monkeyspeak.sln
script:
  - xbuild /p:Configuration=Release Monkeyspeak/Monkeyspeak.csproj