language: csharp
solution: Monkeyspeak.sln
sudo: required
dist: trusty
bundler_args: "--retry 5"
mono: latest

#branches:
#  except:
#    - /^*-v[0-9]/

notifications:
    email:
        recipients:
            - $(EMAIL)
        on_success: never
        on_failure: always

before_install:
- sudo apt-get install rar

install:
- nuget install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
- nuget restore Monkeyspeak.sln

script:
- msbuild /p:Configuration=Release /langversion:default Monkeyspeak/Monkeyspeak.csproj
- msbuild /p:Configuration=Release /langversion:default msxc/msxc.csproj
- msbuild /p:Configuration=Release /langversion:default Monkeyspeak.Tests/Monkeyspeak.Tests.csproj
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./Monkeyspeak.Tests/bin/Release/Monkeyspeak.Tests.dll

