version: 7.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_branch_with_pr: false

environment:
  EMAIL:
    secure: 5DsdNYTfa5eNrxsF2bEIiSajS0B0I28NIpNPewvCoZA=
  GITHUB_AUTH:
    secure: DtORb8qbALfHiPYvK7K0ncfYc4MFNiXiF562/zzHlqvM4/p13nAS6zJKwYhxB+4Y

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

test:
  assemblies:
    - '**\*.Tests.dll'

before_build:
    - choco install winrar
    - nuget restore Monkeyspeak.sln

build:
  project: Monkeyspeak.sln
  publish_nuget: false
  include_nuget_references: false
  parallel: true
  verbosity: minimal

artifacts:
    - path: **/*.rar
    name: rars
# Deploy to GitHub Releases
deploy:
  - provider: GitHub
    artifact: rars           # upload all rars to release assets
    draft: false
    prerelease: false
    force_update: true
    release: "{version}"
    description: Monkeyspeak Release
    auth_token:
        secure: $GITHUB_AUTH # your encrypted token from GitHub
    on:
        branch: master                 # release from master branch only
        appveyor_repo_tag: true        # deploy on tag push only

notifications:
- provider: Email
  to:
  - $EMAIL
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false