version: 1.0.{build}
branches:
  only:
  - master
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - moo2_1@hotmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false