version: 7.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_branch_with_pr: false

environment:
  EMAIL:
    secure: 5DsdNYTfa5eNrxsF2bEIiSajS0B0I28NIpNPewvCoZA=

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules
  - '%LocalAppData%\NuGet\v3-cache

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  project: Monkeyspeak.sln
  publish_nuget: false
  include_nuget_references: false
  parallel: true
  verbosity: minimal

notifications:
- provider: Email
  to:
  - $(EMAIL)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false